ARG base_image=cimg/clojure:1.10-node
FROM ${base_image}

default:
  FROM ${base_image}
  RUN --no-cache date

INSTALL_NODE:
  COMMAND
  ARG npm_version
  RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash - \
      && apt-get install -y nodejs \
      && rm -rf /var/lib/apt/lists/*
  RUN npm install -g npm@${npm_version}
  # RUN npm install -g yarn
  RUN npm install -g karma-cli

INSTALL_KONDO:
  COMMAND
  ARG kondo_version
  RUN curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo \
      && chmod +x install-clj-kondo \
      && echo Version: $${kondo_version} \
      && ./install-clj-kondo --version ${kondo_version} \
      && rm -f install-clj-kondo

INSTALL_BABASHKA:
  COMMAND
  # FIXME: This always downloads the latest version, enable pinning
  RUN curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install \
      && chmod +x install \
      && ./install \
      && rm -f install

babashka-base:
  ARG base_image
  ARG src_home
  FROM ${base_image?}
  WORKDIR ${src_home?}
  USER root
  DO +INSTALL_BABASHKA

INSTALL_CHROMIUM:
  COMMAND
  RUN snap install chromium-browser
  # RUN apt update && apt install -y \
  #         chromium-browser \
  #     && rm -rf /var/lib/apt/lists/*
  ENV CHROME_BIN=chromium-browser

portal:
  RUN --no-cache echo "building portal"
