---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: duck1123/dinsro-dev
  commands:
  - npm install
  - npm install -g karma-cli
  - mkdir -p /dinsro/test
  - cp test-config.edn.example test-config.edn
  - script/test
  - script/test-javascript
- name: build
  image: duck1123/dinsro-dev
  commands:
  - script/build-production
- name: docker
  image: plugins/docker
  settings:
    repo: duck1123/dinsro
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password
---
kind: secret
name: username
get:
  path: dockerhub-creds
  name: DOCKERHUB_USERNAME
---
kind: secret
name: password
get:
  path: dockerhub-creds
  name: DOCKERHUB_PASSWORD
