stages:
- name: Build
  steps:
  - runScriptConfig:
      image: theasp/clojurescript-nodejs:latest
      shellScript: |-
        script/lint
        script/test
        script/test-javascript
        script/build-production
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: duck1123/dinsro:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
