stages:
- name: Build
  steps:
  - runScriptConfig:
      image: theasp/clojurescript-nodejs:latest
      shellScript: |-
        script/build-production
- name: Publish Builder
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: duck1123/dinsro:${CICD_EXECUTION_SEQUENCE}
