stages:
- name: Publish Builder
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile-dev
      buildContext: .
      tag: duck1123/dinsro-dev:${CICD_EXECUTION_SEQUENCE}
- name: Build
  steps:
  - runScriptConfig:
      image: duck1123/dinsro-dev:${CICD_EXECUTION_SEQUENCE}
      shellScript: |-
        script/build-production
        script/docker
