stages:
- name: Build
  steps:
  - runScriptConfig:
      image: circleci/clojure:openjdk-14-lein-2.9.1-buster-node-browsers-legacy
      shellScript: |-
        script/build-production
- name: Publish Builder
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: duck1123/dinsro:${CICD_EXECUTION_SEQUENCE}
