version: '3.3'

services:
  dinsro:
    image: duck1123/dinsro:2-dev-sources-latest
    depends_on:
    - frontend
    ports:
    - 3001:3000
    - 7001:7000
    volumes:
    - ".:/usr/src/app"
    - "${HOME}/.m2:/home/dinsro/.m2"
    - "./data:/var/lib/dinsro/data"

  watch:
    image: duck1123/dinsro:2-dev-sources-latest
    command: ["make", "watch-cljs"]
    depends_on:
    - frontend
    volumes:
    - ".:/usr/src/app"
    - "${HOME}/.m2:/home/dinsro/.m2"
    - "./data:/var/lib/dinsro/data"
    ports:
    - 9630:9630
    labels:
    - "traefik.http.routers.watch.rule=host(`watch-dinsro.docker.localhost`)"
    - "traefik.http.routers.watch.service=watch"
    - "traefik.http.services.watch.loadbalancer.server.port=9630"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9630"]
      timeout: 10s
      retries: 30

  workspaces:
    image: duck1123/dinsro:2-dev-sources-latest
    command: ["make", "dev-workspaces-bootstrap"]
    depends_on:
    - frontend
    volumes:
    - ".:/usr/src/app"
    - "${HOME}/.m2:/home/dinsro/.m2"
    - "./data:/var/lib/dinsro/data"
    ports:
    - 9634:9630
    labels:
    - "traefik.http.routers.workspaces.rule=host(`workspaces-dinsro.docker.localhost`)"
    - "traefik.http.routers.workspaces.service=workspaces"
    - "traefik.http.services.workspaces.loadbalancer.server.port=3693"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3693"]
      timeout: 10s
      retries: 30

  frontend:
    image: traefik:v2.0
    working_dir: "/usr/src/app"
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - ${PWD}/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
