# .circleci/config.yml

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS"
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - run: earthly --version
      - run: earthly --remote-cache=duck1123/dinsro:cache +ci
      - run: earthly --remote-cache=duck1123/dinsro:cache --push +image
