version: 2
jobs:
  build:
    working_directory: ~/dinsro
    docker:
      - image: circleci/clojure:lein-2.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dinsro-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: dinsro-{{ checksum "project.clj" }}
      - run: script/lint
      - run: script/test
      # - run: script/test-javascript
      - run: script/build-production
      - store_artifacts:
          path: target/uberjar/dinsro.jar
          destination: uberjar
