version: 2
jobs:
  build:
    working_directory: ~/dinsro
    docker:
      - image: circleci/clojure:openjdk-14-lein-2.9.1-buster-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          keys:
            - dinsro-{{ checksum "project.clj" }}
      - restore_cache:
          keys:
            - node-{{ checksum "package.json" }}
      - run: node --version
      - run: npm install
      - save_cache:
          paths:
            - ~/dinsro/node_modules
          key: node-{{ checksum "package.json" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: dinsro-{{ checksum "project.clj" }}
      - run: script/lint
      - run: cp test-config.edn.example test-config.edn
      - run: script/test
      # - run: script/test-javascript
      - run: script/build-production
      - store_artifacts:
          path: target/uberjar/dinsro.jar
          destination: dinsro.jar
