apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinsro
  labels:
    app: dinsro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinsro
      release: dinsro
  template:
    metadata:
      labels:
        app: dinsro
        release: dinsro
    spec:
      containers:
      - name: dinsro
        image: duck1123/dinsro:dev-sources-latest
        imagePullPolicy: Always
        env:
          - name: DATAHIKE_URL
            value: "datahike:file:///var/lib/dinsro/data"
        ports:
        - name: dinsro
          containerPort: 3000
