apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: dinsro
      tier: frontend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: dinsro
        tier: frontend
    spec:
      containers:
      - name: dinsro
        image: duck1123/dinsro:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        env:
        - name: DATAHIKE_URL
          value: datahike:file:///dinsro/data
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: data
          mountPath: /dinsro/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
