kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  labels:
    app: dinsro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "local-path"
