apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: dinsro
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 3000
  selector:
    app: dinsro
    tier: frontend
